---
- hosts: ada
  user: root
  strategy: free

  # Falta ubridge
  vars:
    grupos: adm,cdrom,dialout,kvm,libvirt,lpadmin,lxd,plugdev,vboxusers

  roles:
    - delete-users
    - lock-sshd
    - swappiness-0
    - role: vasilisa
      vars:
        sirin: "http://192.168.17.18:8000/launcher/?label=ada-u2204.yml"
    - activate-unattended-upgrades
    - role: cambia-hostname
      vars:
        base_hostname: "ada"
    - ubuntu-desktop-minimal
    - software
    - firefox-cambia-snap-por-flatpak
    - gnome-dconf-2204
    - apache-userdir
    - wireshark
      #- dotnet
    - kvm
    - lxd-dir
    - glpi-agent
    - convidat
    - apagado-1455
    - apagado-2130

  tasks:
    # Usuarios
    - include: users/informatica/alumnos/smx2a.yml
    - include: users/informatica/alumnos/asix2a.yml
    #- include: users/informatica/smx2c.yml
