---
- hosts: aif
  user: root

  vars:
    grupos: adm,cdrom,dialout,kvm,libvirt,lpadmin,lxd,plugdev,sambashare,ubridge,vboxusers

  roles:
    - delete-users
    - lock-sshd
    - zsys-gc
    - swappiness-0
    - role: vasilisa
      vars:
        sirin: "http://192.168.14.18:8000/launcher/?label=aif-u2004.yml"
    - activate-unattended-upgrades
    - role: cambia-hostname
      vars:
        base_hostname: "aif"
    - gnome3-dconf
    - software-2004
    - apache-userdir
    - wireshark
    - gns3
    - dotnet
    - kvm
    - lxd-zfs
    - convidat
    - apagado-1455
    - apagado-2130

  tasks:
    # Usuarios
    - include: users/aig/alumnos/1aga.yml
    - include: users/aig/alumnos/1bga.yml
    - include: users/aig/alumnos/2ga.yml
    - include: users/aig/alumnos/afcat.yml
      #- include: users/aig/xavic.yml
