---
- hosts: aif
  user: root
  strategy: free

  vars:
    grupos: adm,cdrom,dialout,kvm,libvirt,lpadmin,lxd,plugdev,vboxusers

  roles:
    - delete-users
    - lock-sshd
    - swappiness-0
    - role: vasilisa
      vars:
        sirin: "http://192.168.14.18:8000/launcher/?label=aif-u2204.yml"
    - activate-unattended-upgrades
    - role: cambia-hostname
      vars:
        base_hostname: "aif"
    - timesyncd-ntp
    - ubuntu-desktop-minimal
    - software
    - firefox-cambia-snap-por-flatpak
    - gnome-dconf-2204
    - apache-userdir
    - wireshark
      #- dotnet
    - kvm
    - lxd-dir
    - glpi-agent
    - convidat
    - apagado-1455
    - apagado-2130

  tasks:
    # Usuarios
    - include: users/aig/alumnos/ga1a.yml
    - include: users/aig/alumnos/ga1b.yml
    - include: users/aig/alumnos/ga2.yml
    - include: users/aig/alumnos/af.yml
    #- include: users/informatica/smx2a.yml
    #- include: users/informatica/smx2b.yml
    #- include: users/informatica/smx2c.yml
