---
- hosts: aif
  user: root

  vars:
    grupos: adm,cdrom,dialout,kvm,libvirt,lpadmin,lxd,plugdev,sambashare,ubridge,vboxusers

  roles:
    - delete-users
    - lock-sshd
    - zsys-gc
    - swappiness-0
    - vasilisa
    - activate-unattended-upgrades
    - role: cambia-hostname
      vars:
        base_hostname: "aif"
    - gnome3-dconf
    - software-2004
    - apache-userdir
    - wireshark
    - gns3
    - dotnet
    - kvm
    - lxd-zfs
    - convidat
    - apagado-1455
    - apagado-2130

  tasks:
    # Usuarios
    - include: users/aig/alumnos/ga1a.yml
    - include: users/aig/alumnos/ga1b.yml
    - include: users/aig/alumnos/ga2.yml
    - include: users/aig/alumnos/afcat.yml
    - include: users/aig/alumnos/afeng.yml
