---
- hosts: ada
  user: root

  tasks:
          - name: Borrado de alumnos
            user:
                    name: "{{ item }}"
                    state: absent
                    remove: true
            loop:
                    - smx2a
                    - asix2a
                    - smx2c
