---
- hosts: delete-users
  user: root
  #strategy: free
  gather_facts: no

  # Borra usuarios con UID > 999
  # Preserva algunos usuarios del sistema que tienen un UID alto
  #
  # Ejemplo: https://stackoverflow.com/questions/37441796/ansible-for-user-management-removing-dead-accounts?answertab=trending#tab-top

  vars:
          myusers: ['convidat', 'libvirt_qemu', 'nobody']

  tasks:
          - name: Lista de usuarios con UID grande
            shell:
                    cmd: "getent passwd | awk -F: '$3 > 999 {print $1}'"
            register: users

          - user: name={{ item }} state=absent remove=yes
            with_items: "{{ users.stdout_lines }}"
            when: item not in myusers

          - name: Apagado
            shell: init 0
            async: 10
            poll: 5

