---
- hosts: snowden
  user: root

  tasks:
          - name: Borrado de alumnos
            user:
                    name: "{{ item }}"
                    state: absent
                    remove: true
            loop:
                    - ga2
                    - smx1c
