---
- hosts: turing
  user: root

  tasks:
          - name: Borrado de alumnos
            user:
                    name: "{{ item }}"
                    state: absent
                    remove: true
            loop:
                    - smx1d
                    - smx2b
