---
- hosts: carret18
  user: root
  strategy: free

  vars:
    grupos: adm,cdrom,dialout,kvm,libvirt,lpadmin,lxd,netdev,plugdev,vboxusers

  roles:
    - delete-users
    - lock-sshd
    - swappiness-0
    - role: vasilisa
      vars:
        sirin: "http://192.168.240.18:8000/launcher/?label=carret18-u2204.yml"
    - activate-unattended-upgrades
    - role: cambia-hostname
      vars:
        base_hostname: "carret18"
    - ubuntu-desktop-minimal
    - software
    - firefox-cambia-snap-por-flatpak
    - gnome-dconf-2204
    - apache-userdir
    - wireshark
      #- dotnet
    - kvm
    - lxd-dir
    - glpi-agent
    - convidat
      #- apagado-1455
      #- apagado-2130

  tasks:
    # Usuarios
    - include: users/esobat/docent.yml
    - include: users/informatica/alumnos/asix2b.yml
    - include: users/informatica/alumnos/smx1c.yml
    #- include: users/informatica/smx2c.yml
