---
- hosts: chomsky
  user: root

  vars:
    grupos: adm,cdrom,dialout,kvm,libvirt,lpadmin,lxd,plugdev,vboxusers

  roles:
    - delete-users
    - lock-sshd
    - zsys-gc
    - swappiness-0
    - role: vasilisa
      vars:
        sirin: "http://192.168.23.18:8000/launcher/?label=chomsky-u2004.yml"
    - activate-unattended-upgrades
    - role: cambia-hostname
      vars:
        base_hostname: "chomsky"
    - gnome3-dconf
    - software-2004
    - apache-userdir
    - wireshark
    - gns3
    - dotnet
    - kvm
    - lxd-zfs
    - broadcom-sta # Los equipos del aula Chomsky necesitan un driver para la wifi
    - glpi-agent
    - convidat
    - apagado-1455
    - apagado-2130

  tasks:
    # Usuarios
    - include: users/aig/alumnos/afcat.yml
    - include: users/aig/alumnos/afeng.yml
    - include: users/idiomes/idiomes.yml
    - include: users/esobat/docent.yml
    #- include: users/informatica/smx2c.yml
