---
- hosts: dpt_fisicaiquimica
  user: root

  vars:
    grupos: adm,cdrom,dialout,kvm,libvirt,lpadmin,lxd,plugdev,sambashare,ubridge,vboxusers

  roles:
    - delete-users
    - lock-sshd
    - zsys-gc
    - swappiness-0
    - role: vasilisa
      vars:
        sirin: "http://192.168.0.18:8000/launcher/?label=dpt-fisicaiquimica-u2004.yml"
    - activate-unattended-upgrades
    - role: cambia-hostname
      vars:
        base_hostname: "dpt-fisicaiquimica"
    - gnome3-dconf
    - software-2004
    - apache-userdir
    - wireshark
    - gns3
    - dotnet
    - kvm
    - lxd-zfs
    - convidat
    #- apagado-1455
    - apagado-2130

  tasks:
    # Usuarios
    - include: users/fisicaiquimica/fisicaiquimica.yml
    #- include: users/informatica/smx2b.yml
    #- include: users/informatica/smx2c.yml
