---
- hosts: dpt-aif
  user: root

  vars:
    grupos: adm,cdrom,dialout,kvm,libvirt,lpadmin,lxd,plugdev,sambashare,ubridge,vboxusers

  roles:
    - delete-users
    - lock-sshd
    - zsys-gc
    - swappiness-0
    - role: vasilisa
      vars:
        sirin: "http://192.168.17.18:8000/launcher/?label=dpt-aif-u2004.yml"
    - activate-unattended-upgrades
    - role: cambia-hostname
      vars:
        base_hostname: "dpt-aif"
    - gnome3-dconf
    - software-2004
    - apache-userdir
    - wireshark
    - gns3
    - dotnet
    - kvm
    - lxd-zfs
    - convidat
#    - apagado-1455
    - apagado-2130

  tasks:
    - include: users/aig/ga.yml
    # Usuarios
    #- include: users/informatica/smx2a.yml
    #- include: users/informatica/smx2b.yml
    #- include: users/informatica/smx2c.yml
