---
- hosts: esobatx_wifi
  user: root
  strategy: free

  vars:
    grupos: adm,cdrom,dialout,kvm,libvirt,lpadmin,lxd,plugdev,vboxusers

  roles:
    - delete-users
    - lock-sshd
    - swappiness-0
    - role: vasilisa
      vars:
        sirin: "http://192.168.240.18:8000/launcher/?label=esobatx_wifi-u2204.yml"
    - activate-unattended-upgrades
    - role: cambia-hostname
      vars:
        base_hostname: "esobatx"
    - timesyncd-ntp
    - ubuntu-desktop-minimal
    - software
    - firefox-cambia-snap-por-flatpak
    - gnome-dconf-2204
    - apache-userdir
    - wireshark
      #- dotnet
    - kvm
    - lxd-dir
    - glpi-agent
    - convidat
    - apagado-1455
    - apagado-2130

  tasks:
    # Usuarios
    - include: users/esobat/docent.yml
    - include: users/informatica/luis.yml
      when: ansible_default_ipv4.address == "192.168.240.176"
    #- include: users/informatica/smx2b.yml
    #- include: users/informatica/smx2c.yml
