---
- hosts: init_portatils_alumnes
  user: root

  vars:
    grupos: adm,cdrom,dialout,lpadmin,netdev,plugdev,sambashare

  roles:
    - delete-users
      #- lock-sshd
      #- zsys-gc
      #- swappiness-0
 
    # Si se ha modificado /etc/default/grub se actualiza grub.
    - pnpacpi-off
    - flush-handlers

    - role: vasilisa
      vars:
        sirin: "http://10.0.0.2:8000/launcher/?label=portatils-alumnes-u2004.yml"
    - wireguard
    
    - activate-unattended-upgrades
    - role: cambia-hostname
      vars:
      base_hostname: "initalumnes"
        
    #- gnome3-dconf
    #- software-2004
    #- apache-userdir
    #- wireshark
    #- gns3
    #- dotnet
    #- kvm
    #- lxd-zfs

    #- convidat
    #- apagado-1455
    #- apagado-2130
    
    - flush-handlers
    #- reboot


  tasks:
    - include: "vpn/{{ vpn }}.yml"
    - name: Activa la VPN wg0 (enable y start)
      systemd:
        name: wg-quick@wg0
        enabled: yes
        state: started
        daemon_reload: yes
    
    - name: Apaga el equipo
      command: systemctl poweroff
      async: 10
      poll: 0

    #- name: Reboot
    #  reboot:

    # Usuarios
    #- include: users/informatica/smx2a.yml
    #- include: users/informatica/smx2b.yml
    #- include: users/informatica/smx2c.yml
