---
- hosts: carretx
  user: root

  vars:
    grupos: adm,cdrom,dialout,kvm,libvirt,lpadmin,lxd,plugdev,sambashare,ubridge,vboxusers

  roles:
    - delete-users
    - lock-sshd
    - zsys-gc
    - swappiness-0
    - role: vasilisa
      vars:
        sirin: "http://10.0.0.2:8000/launcher/?label=carret14-u2004.yml"
    - wireguard
    
    - activate-unattended-upgrades
    - role: cambia-hostname
      vars:
        base_hostname: "carretx"
    - gnome3-dconf
    - software-2004
    - apache-userdir
    - wireshark
    - gns3
    - dotnet
    - kvm
    - lxd-zfs
    #- convidat
    #- apagado-1455
    #- apagado-2130
    
    - reboot


  tasks:
    - include: "vpn/{{ vpn }}.yml"
    - name: Activa la VPN wg0 (enable y start)
      systemd:
        name: wg-quick@wg0
        enabled: yes
        state: started
    
    # Usuarios
    #- include: users/informatica/smx2a.yml
    #- include: users/informatica/smx2b.yml
    #- include: users/informatica/smx2c.yml
