---
- hosts: init-docents
  user: root
  strategy: free

  vars:
    grupos: adm,cdrom,dialout,lpadmin,plugdev

  roles:
    - delete-users
    - lock-sshd
    - swappiness-0
    - role: vasilisa
      vars:
        sirin: "http://10.0.0.2:8000/launcher/?label=portatils-docents-u2204.yml"
    - activate-unattended-upgrades
    - role: cambia-hostname
      vars:
        base_hostname: "docent"
        #- ubuntu-desktop-minimal
        #- software
        #- firefox-cambia-snap-por-flatpak
        #- gnome-dconf-2204
        #- apache-userdir
        #- wireshark
      #- dotnet
      #- kvm
      #- lxd-dir
    - glpi-agent
      #- convidat
      #- apagado-1455
      #- apagado-2130
      
    - flush-handlers

  tasks:
    - name: Instala wireguard-tools
      apt:
        name: wireguard-tools
        state: present

    - include: "vpn/{{ vpn }}.yml"

    - name: Activa la VPN wg0 (enable y start)
      systemd:
        name: wg-quick@wg0
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Reboot
      reboot:
