---
- hosts: portatils_alumnes_f34
  user: root

  vars:
    grupos: adm,cdrom,dialout,netdev,plugdev,sambashare

  roles:
    - delete-users
    - lock-sshd
    - role: vasilisa
      vars:
        sirin: "http://10.0.0.2:8000/launcher/?label=portatils-alumnes-u2004.yml"
    - role: cambia-hostname-wg0
      vars:
        base_hostname: "alumne"
    - wireguard
    #- convidat
    #- apagado-1455
    #- apagado-2130
    - flush-handlers

  tasks:
    # Cada equipo tiene un usuario particular
    - include: "vpn/{{ vpn }}.yml"

    - name: Activa la VPN wg0 (enable y start)
      systemd:
        name: wg-quick@wg0
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Apaga el equipo
      command: systemctl poweroff
      async: 10
      poll: 0


    # Usuarios
    #- include: users/informatica/smx2a.yml
    #- include: users/informatica/smx2b.yml
    #- include: users/informatica/smx2c.yml
