---
- hosts: tesla
  user: root

  vars:
    grupos: adm,cdrom,dialout,kvm,libvirt,lpadmin,lxd,plugdev,sambashare,ubridge,vboxusers

  roles:
    - delete-users
    - lock-sshd
    - zsys-gc
    - swappiness-0
    - role: vasilisa
      vars:
        sirin: "http://192.168.22.18:8000/launcher/?label=tesla-u2004.yml"
    - activate-unattended-upgrades
    - role: cambia-hostname
      vars:
        base_hostname: "tesla"
    - gnome3-dconf
    - software-2004
    - apache-userdir
    - wireshark
    - gns3
    - dotnet
    - kvm
    - lxd-zfs
    - glpi-agent
    - convidat
    - apagado-1455
    - apagado-2130

  tasks:
    # Usuarios
    - include: users/informatica/delete-users.yml
    - include: users/informatica/alumnos/dam2a.yml
    - include: users/esobat/grupos/tec3a-g1.yml
    - include: users/esobat/grupos/tec3a-g2.yml
    - include: users/esobat/grupos/tec3b-g1.yml
    - include: users/esobat/grupos/tec3b-g2.yml
    - include: users/esobat/grupos/tec3c-g1.yml
    - include: users/esobat/grupos/tec3c-g2.yml
    - include: users/esobat/grupos/tec3d-g1.yml
    - include: users/esobat/grupos/tec3d-g2.yml
    - include: users/esobat/grupos/tec3e-g1.yml
    - include: users/esobat/grupos/tec3e-g2.yml
    - include: users/esobat/grupos/robo2.yml
    - include: users/esobat/grupos/inf-fiii.yml
    - include: users/esobat/grupos/inf-fiv.yml
    - include: users/esobat/grupos/tec2-fi.yml
