- name: Instala lxd
  snap:
        name: lxd
  ignore_errors: yes
  notify:
    - copy lxd-preseed
    - config lxd
    - config firewall

- name: Crea el grupo lxd
  group:
    name: lxd
    system: true
    state: present
