#!/bin/bash

#
# Tareas periódicas en el carret 10
#

playbooks="/home/vcarceler/playbooks-ubuntu2004"

export ANSIBLE_CALLBACK_PLUGINS="$(python3 -m ara.setup.callback_plugins)"

ansible-playbook -i $playbooks/hosts $playbooks/carret10-u2004.yml
