#
# Instalación general de software para Ubuntu 20.04 LTS
#


- name: Desinstala paquetes deprecated
  apt:
    state: absent
    pkg:
      - openscad
      - virtualbox-6.1
#       - chromium-browser
#       - chromium-browser-l10n
#       - arduino
#       - arduino-core
#       - krita
#       - krita-l10n

- name: Elimina snaps deprecated
  snap:
          state: absent
          name:
                  - atom
                  - blender
                  - bluej
                  - brackets
                  - darktable
                  - flameshot
                  - gimp
                  - godot-3-1
                  - inkscape
                  - kbruch
                  - kcalc
                  - kdenlive
                  - kig
                  - ktouch
                  - krita
                  - librepcb
                  - musescore
                  - mysql-workbench-community
                  - natron
                  - octave
                  - obs-studio
                  - pdfmixtool
                  - qalculate
                  - ruby
                  - shotcut
                  - syncthing
                  - sweethome3d-homedesign
                  - vlc

#- name: Instala snap atom
#  snap:
#        name: atom
#        classic: yes

- name: Instala snap beekeeper-studio
  snap:
        name: beekeeper-studio

#- name: Instala snap blender
#  snap:
#        name: blender
#        classic: yes

#- name: Instala snap bluej
#  snap:
#        name: bluej

#- name: Instala snap brackets
#  snap:
#        name: brackets
#        classic: yes

#- name: Instala snap brave
#  snap:
#        name: brave

#- name: Instala snap chromium
#  snap:
#        name: chromium

- name: Instala snap cura-slicer
  snap:
        name: cura-slicer

#- name: Instala snap darktable
#  snap:
#        name: darktable

- name: Instala snap eclipse
  snap:
        name: eclipse
        classic: yes

#- name: Instala godot-3-1
#  snap:
#        name: godot-3-1
#        channel: edge

#- name: Instala snap inkscape
#  snap:
#        name: inkscape

- name: Instala snap intellij-idea-educational
  snap:
        name: intellij-idea-educational
        classic: yes

- name: Instala snap jupyter
  snap:
        name: jupyter

- name: Instala snap kalgebra
  snap:
        name: kalgebra

#- name: Instala snap kbruch
#  snap:
#        name: kbruch

#- name: Instala snap kcalc
#  snap:
#        name: kcalc

#- name: Instala snap kdenlive
#  snap:
#        name: kdenlive

#- name: Instala snap kig
#  snap:
#        name: kig   

- name: Instala snap kmplot
  snap:
        name: kmplot

- name: Instala snap kotlin
  snap:
        name: kotlin
        classic: yes

#- name: Instala snap krita
#  snap:
#        name: krita

#- name: Instala snap ktouch
#  snap:
#        name: ktouch

#- name: Instala snap librepcb
#  snap:
#        name: librepcb

#- name: Instala snap musescore
#  snap:
#        name: musescore

#- name: Instala snap natron
#  snap:
#        name: natron

- name: Instala snap netbeans
  snap:
        name: netbeans
        classic: yes

- name: Instala snap node
  snap:
        name: node
        classic: yes
        channel: edge

- name: Instala snap node-red
  snap:
        name: node-red

#- name: Instala snap obs-studio
#  snap:
#        name: obs-studio

#- name: Instala snap octave
#  snap:
#        name: octave

#- name: Instala snap pdfmixtool
#  snap:
#        name: pdfmixtool

- name: Instala snap pdftk
  snap:
        name: pdftk

#- name: Instala snap qalculate
#  snap:
#        name: qalculate

#- name: Instala snap shotcut
#  snap:
#        name: shotcut
#        classic: yes

#- name: Instala snap sweethome3d-homedesign
#  snap:
#        name: sweethome3d-homedesign

#- name: Instala snap syncthing
#  snap:
#        name: syncthing

- name: Instala snap umbrello
  snap:
        name: umbrello

#- name: Instala snap vlc
#  snap:
#        name: vlc       

- name: Instala snap code
  snap:
        name: code
        classic: yes

# Actualiza a la última versión
- name: Actualiza a la última versión
  apt:
    state: latest
    update_cache: yes
    pkg: 
      - firefox
      - firefox-locale-ca
      - flashplugin-installer
      - net-tools
      - vim
  ignore_errors: True
  register: result
  when: ansible_distribution_version == "20.04"

- name: Si es necesario ejecuta 'dpkg --configure -a'
  shell: dpkg --configure -a
  when: result is failed

#
# Añade PPA Flatpak ppa:alexlarsson/flatpak y configura 50unattended-upgrades
#
- name: Instala PPA Flatpak ppa:alexlarsson/flatpak
  apt_repository:
    repo: ppa:alexlarsson/flatpak
  when: ansible_distribution_version == "20.04"

- name: Añade LP-PPA-alexlarsson-flatpak:focal a /etc/apt/apt.conf.d/50unattended-upgrades
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    insertafter: '^Unattended-Upgrade::Allowed-Origins'
    line: '        "LP-PPA-alexlarsson-flatpak:focal";'
  when: ansible_distribution_version == "20.04"

# Instalación de paquetes
- name: Instalación de paquetes que están en los repos de 18.04 y 20.04
  apt:
    update_cache: yes
    pkg:
            #- audacity
    - default-jdk
    - dia
    - dia-rib-network
    - dia-shapes
    - dia2code
    - dialog
    - docutils-doc
      #- filezilla
    - flatpak
    - flatpak-builder
      #- freecad
      #- fritzing
    - git
    - gnome-boxes
    - golang-go
    - htop
    - httpie
    - ipcalc
    - jq
      #- kicad
      #- kicad-doc-es
    - korganizer
    - librecad
    - libreoffice-base
    - libreoffice-report-builder
    - lyx
    - ncdu
    - openshot
      # No está en el 21.04
      #- pgadmin3
    - planner
    - prometheus-node-exporter
    - pylint
    - pylint3    
    - python3-docutils
    - python3-easygui
    - python3-pip
    - python3-pylint-django
    - python3-pypdf2
    - recordmydesktop
    - relational
    - rst2pdf
    - ripgrep
    - ruby
    - scratch
    - slic3r
    - texlive-lang-spanish
    - tree
    - tshark
    - ttf-mscorefonts-installer
    - unrar
    - virt-top
    - virtualbox
    - virtualenv
    - vpcs
    - xorriso

# Desactiva el collector de systemd porque tiene una cardinalidad muy alta
# https://www.robustperception.io/dropping-metrics-at-scrape-time-with-prometheus
- name: Aplica --no-collector.systemd en /etc/default/prometheus-node-exporter
  replace:
    dest: /etc/default/prometheus-node-exporter
    regexp: '^ARGS=""'
    replace: 'ARGS="--no-collector.systemd"'

# Instalación de paquetes
- name: Instalación de paquetes que solo están en 20.04
  apt:
    update_cache: yes
    pkg:
            #- openscad
    - julia
  when: ansible_distribution_version == "20.04"

# Instalación de paquetes
- name: Instalación de paquetes que solo están en 21.04
  apt:
    update_cache: yes
    pkg:
    - julia
    - podman
    - vim
  when: ansible_distribution_version == "21.04"

# Cambio de Virtualbox. Se desinstala la versión de los repos y se instala la versión de Oracle.
#- name: Quita Virtualbox 6.1 de los repos
#  apt:
#    state: absent
#    pkg:
#      - virtualbox
#      - virtualbox-dkms

#- name: Copia paquete de Virtualbox
#  copy:
#    src: /home/vcarceler/playbooks-ubuntu2004/files/virtualbox-6.1_6.1.16-140961~Ubuntu~eoan_amd64.deb
#    dest: /opt

#- name: Instala Virtualbox libre de Oracle
#  apt:
#    deb: /opt/virtualbox-6.1_6.1.16-140961~Ubuntu~eoan_amd64.deb 


# Instalación de paquetes Flatpak

- name: Instala flatpak de arduino-ide
  flatpak:
          name: https://dl.flathub.org/repo/appstream/cc.arduino.arduinoide.flatpakref
          state: present

- name: Instala flatpak de atom
  flatpak:
          name: https://dl.flathub.org/repo/appstream/io.atom.Atom.flatpakref
          state: present

- name: Instala flatpak de audacity
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.audacityteam.Audacity.flatpakref
          state: present

- name: Instala flatpak de blender
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.blender.Blender.flatpakref
          state: present

- name: Instala flatpak de bluej
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.bluej.BlueJ.flatpakref
          state: present

          #- name: Instala flatpak de brackets
          #flatpak:
          #name: https://dl.flathub.org/repo/appstream/io.brackets.Brackets.flatpakref
          #state: present

- name: Instala flatpak de calibre
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.calibre_ebook.calibre.flatpakref
          state: present

- name: Instala flatpak de chromium
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.chromium.Chromium.flatpakref
          state: present

- name: Instala flatpak de darktable
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.darktable.Darktable.flatpakref
          state: present

- name: Instala flatpak de dbeaver
  flatpak:
          name: https://dl.flathub.org/repo/appstream/io.dbeaver.DBeaverCommunity.flatpakref
          state: present

- name: Instala flatpak de filezilla
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.filezillaproject.Filezilla.flatpakref
          state: present

- name: Instala flatpak de flameshot
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.flameshot.Flameshot.flatpakref
          state: present

- name: Instala flatpak de freecad
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.freecadweb.FreeCAD.flatpakref
          state: present

- name: Instala flatpak de fritzing
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.fritzing.Fritzing.flatpakref
          state: present

- name: Instala flatpak de gaphor
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.gaphor.Gaphor.flatpakref
          state: present

- name: Instala flatpak de geogebra
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.geogebra.GeoGebra.flatpakref
          state: present

- name: Instala flatpak de gimp
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.gimp.GIMP.flatpakref
          state: present

- name: Instala flatpak de godot
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.godotengine.Godot.flatpakref
          state: present

- name: Instala flatpak de inkscape
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.inkscape.Inkscape.flatpakref
          state: present

- name: Instala flatpak de herramientas kde
  flatpak:
          state: present
          name: "{{ item  }}"
  loop:
          - https://dl.flathub.org/repo/appstream/org.kde.kbruch.flatpakref
          - https://dl.flathub.org/repo/appstream/org.kde.kcalc.flatpakref
          - https://dl.flathub.org/repo/appstream/org.kde.kdenlive.flatpakref
          - https://dl.flathub.org/repo/appstream/org.kde.kig.flatpakref
          - https://dl.flathub.org/repo/appstream/org.kde.ktouch.flatpakref

- name: Instala flatpak de kicad
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.kicad.KiCad.flatpakref
          state: present

- name: Instala flatpak de krita
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.kde.krita.flatpakref
          state: present

- name: Instala flatpak de libreoffice
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.libreoffice.LibreOffice.flatpakref
          state: present

- name: Instala flatpak de librepcb
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.librepcb.LibrePCB.flatpakref
          state: present

- name: Instala flatpak de maps
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.gnome.Maps.flatpakref
          state: present

- name: Instala flatpak de musescore
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.musescore.MuseScore.flatpakref
          state: present

- name: Instala flatpak de natron
  flatpak:
          name: https://dl.flathub.org/repo/appstream/fr.natron.Natron.flatpakref
          state: present

- name: Instala flatpak de octave
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.octave.Octave.flatpakref
          state: present

- name: Instala flatpak de openscad
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.openscad.OpenSCAD.flatpakref
          state: present

- name: Instala flatpak de plots
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.github.alexhuntley.Plots.flatpakref
          state: present

- name: Instala flatpak de obs-studio
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.obsproject.Studio.flatpakref
          state: present

- name: Instala flatpak de openboard
  flatpak:
          name: https://dl.flathub.org/repo/appstream/ch.openboard.OpenBoard.flatpakref
          state: present

- name: Instala flatpak de passwordsafe
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.gnome.PasswordSafe.flatpakref
          state: present

- name: Instala flatpak de pdfarranger
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.github.jeromerobert.pdfarranger.flatpakref
          state: present

- name: Instala flatpak de pdfmixtool
  flatpak:
          name: https://dl.flathub.org/repo/appstream/eu.scarpetta.PDFMixTool.flatpakref
          state: present

- name: Instala flatpak de peek
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.uploadedlobster.peek.flatpakref
          state: present

- name: Instala flatpak de prusaslicer
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.prusa3d.PrusaSlicer.flatpakref
          state: present

- name: Instala flatpak de qalculate
  flatpak:
          name: https://dl.flathub.org/repo/appstream/io.github.Qalculate.flatpakref
          state: present

- name: Instala flatpak de sweethome3d
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.sweethome3d.Sweethome3d.flatpakref
          state: present

- name: Instala flatpak de shotcut
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.shotcut.Shotcut.flatpakref
          state: present

- name: Instala flatpak de vlc
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.videolan.VLC.flatpakref
          state: present
