#
# Instalación general de software para Ubuntu 20.04 LTS
#


# - name: Desinstala paquetes que han sido substituidos por snaps
#   apt:
#     state: absent
#     pkg:
#       - chromium-browser
#       - chromium-browser-l10n
#       - arduino
#       - arduino-core
#       - krita
#       - krita-l10n


- name: Instala snap atom
  snap:
        name: atom
        classic: yes

- name: Instala snap blender
  snap:
        name: blender
        classic: yes

- name: Instala snap brackets
  snap:
        name: brackets
        classic: yes

- name: Instala snap chromium
  snap:
        name: chromium

- name: Instala snap darktable
  snap:
        name: darktable

- name: Instala snap gimp
  snap:
        name: gimp

- name: Instala godot-3-1
  snap:
        name: godot-3-1
        channel: edge

- name: Instala snap inkscape
  snap:
        name: inkscape

- name: Instala snap intellij-idea-educational
  snap:
        name: intellij-idea-educational
        classic: yes

- name: Instala snap jupyter
  snap:
        name: jupyter

- name: Instala snap kalgebra
  snap:
        name: kalgebra

- name: Instala snap kbruch
  snap:
        name: kbruch

- name: Instala snap kcalc
  snap:
        name: kcalc

- name: Instala snap kdenlive
  snap:
        name: kdenlive

- name: Instala snap kig
  snap:
        name: kig   

- name: Instala snap kmplot
  snap:
        name: kmplot

- name: Instala snap krita
  snap:
        name: krita

- name: Instala snap ktouch
  snap:
        name: ktouch

- name: Instala snap librepcb
  snap:
        name: librepcb

- name: Instala snap musescore
  snap:
        name: musescore

- name: Instala snap node
  snap:
        name: node
        classic: yes
        channel: edge

- name: Instala snap obs-studio
  snap:
        name: obs-studio

- name: Instala snap octave
  snap:
        name: octave

- name: Instala snap pdfmixtool
  snap:
        name: pdfmixtool

- name: Instala snap pdftk
  snap:
        name: pdftk

- name: Instala snap qalculate
  snap:
        name: qalculate

- name: Instala snap shotcut
  snap:
        name: shotcut
        classic: yes

- name: Instala snap sweethome3d-homedesign
  snap:
        name: sweethome3d-homedesign

- name: Instala snap syncthing
  snap:
        name: syncthing

- name: Instala snap vlc
  snap:
        name: vlc       

- name: Instala snap vscode
  snap:
        name: code
        classic: yes

# Actualiza a la última versión
- name: Actualiza a la última versión
  apt:
    state: latest
    update_cache: yes
    pkg: 
      - firefox
      - firefox-locale-ca
      - flashplugin-installer
      - net-tools
      - vim
  ignore_errors: True
  register: result

- name: Si es necesario ejecuta 'dpkg --configure -a'
  shell: dpkg --configure -a
  when: result is failed

# Instalación de paquetes
- name: Instalación de paquetes
  apt:
    update_cache: yes
    pkg:
    - audacity
    - ncdu
    - freecad
    - fritzing
    - gnome-boxes
    - golang-go
    - httpie
    - korganizer
    - kicad
    - kicad-doc-es
    - libguestfs-tools
    - libreoffice-base
    - libreoffice-report-builder
    - lyx
    - texlive-lang-spanish
    - ipcalc
    - librecad
    - default-jdk
    - slic3r
    - openshot
    - ovmf
    - planner
    - prometheus-node-exporter
    - pylint
    - pylint3
    - python3-pylint-django
    - python3-pip
    - relational
    - scratch
    - ttf-mscorefonts-installer
    - virt-top
    - pgadmin3
    - dialog
    - vpcs
    - recordmydesktop
    - git
    - virtualbox
    - virtualenv
    - python3-docutils
    - docutils-doc
    - filezilla
    - unrar
    - dia
    - dia2code
    - dia-rib-network
    - dia-shapes
    - rst2pdf
    - python3-pypdf2
    - tshark
    - xorriso