#
# Instalación general de software para Ubuntu 20.04 LTS y Fedora 34
#

- name: Gestiona aplicaciones en flatpak
  include_role:
    name: flatpaks
  tags:
    - slow

- name: Gestiona aplicaciones en snap
  include_role:
    name: snaps
  tags:
    - slow

- name: Gestiona paquetes en Ubuntu
  include_role:
    name: paquetes-ubuntu
  when: ansible_distribution_version == "20.04"

- name: Gestiona paquetes en Fedora
  include_role:
    name: paquetes-fedora
  when: ansible_distribution_version == "34"

# Actualiza a la última versión
#- name: Actualiza a la última versión
#  apt:
#    state: latest
#    update_cache: yes
#    pkg: 
#      - firefox
#      - firefox-locale-ca
#      - flashplugin-installer
#      - net-tools
#      - vim
#  ignore_errors: True
#  register: result
#  when: ansible_distribution_version == "20.04"

#- name: Si es necesario ejecuta 'dpkg --configure -a'
#  shell: dpkg --configure -a
#  when: result is failed


# Cambio de Virtualbox. Se desinstala la versión de los repos y se instala la versión de Oracle.
#- name: Quita Virtualbox 6.1 de los repos
#  apt:
#    state: absent
#    pkg:
#      - virtualbox
#      - virtualbox-dkms

#- name: Copia paquete de Virtualbox
#  copy:
#    src: /home/vcarceler/playbooks-ubuntu2004/files/virtualbox-6.1_6.1.16-140961~Ubuntu~eoan_amd64.deb
#    dest: /opt

#- name: Instala Virtualbox libre de Oracle
#  apt:
#    deb: /opt/virtualbox-6.1_6.1.16-140961~Ubuntu~eoan_amd64.deb 

