#!/bin/bash

#
# Tareas periódicas en el Aula Chomsky
#

playbooks="/home/vcarceler/playbooks-ubuntu2004"

export ANSIBLE_CALLBACK_PLUGINS="$(python3 -m ara.setup.callback_plugins)"

ansible-playbook -i $playbooks/hosts $playbooks/chomsky-u2004.yml
