#!/bin/bash

#
# Tareas periódicas en el dpt-inf
#

playbooks="/home/vcarceler/playbooks-ubuntu2004"

export ANSIBLE_CALLBACK_PLUGINS="$(python3 -m ara.setup.callback_plugins)"

ansible-playbook -i $playbooks/hosts $playbooks/dpt-inf-u2004.yml
ansible-playbook -i $playbooks/hosts $playbooks/users/informatica/profesinf-users.yml
