#!/bin/bash

#
# Tareas periódicas en el dpt-religio
#

playbooks="/home/vcarceler/playbooks-ubuntu2004"

export ANSIBLE_CALLBACK_PLUGINS="$(python3 -m ara.setup.callback_plugins)"

ansible-playbook -i $playbooks/hosts $playbooks/dpt-religio-u2004.yml
