#!/bin/bash

#
# Tareas periódicas en lenovo-v510
#

playbooks="/home/vcarceler/playbooks-ubuntu2004"

export ANSIBLE_CALLBACK_PLUGINS="$(python3 -m ara.setup.callback_plugins)"

ansible-playbook -i $playbooks/hosts $playbooks/lenovo-v510-u2004.yml
