#!/bin/bash

#
# Tareas periódicas en el Aula Turing
#

playbooks="/home/vcarceler/playbooks-ubuntu2004"

export ANSIBLE_CALLBACK_PLUGINS="$(python3 -m ara.setup.callback_plugins)"

ansible-playbook -i $playbooks/hosts $playbooks/usuario-amacias-u2004.yml
