#!/bin/bash

#
# Procesa las peticiones pendientes para cada una de las etiquetas.
#

# venv's python
PYTHON="/home/vcarceler/sirin/venv/bin/python"
# Sirin's manage.py
MANAGE="/home/vcarceler/sirin/sirin/manage.py"

# ARA
playbooks="/home/vcarceler/playbooks-ubuntu2004"
export ANSIBLE_CALLBACK_PLUGINS="$(python3 -m ara.setup.callback_plugins)"

for x in ada-u2004.yml aif-u2004.yml biblioteca-u2004.yml carret14-u2004.yml chomsky-u2004.yml consergeria-u2004.yml dpt-aif-u2004.yml dpt-cast-u2004.yml dpt-cat-u2004.yml dpt-ciencies-u2004.yml dpt-ciencies-lab-u2004.yml dpt-dibuix-u2004.yml dpt-edufis-u2004.yml dpt-erasmus-u2004.yml dpt-filosofia-u2004.yml dpt-fisicaiquimica-u2004.yml dpt-historia-u2004.yml dpt-inf-u2004.yml dpt-ing-u2004.yml dpt-mat-u2004.yml dpt-musica-u2004.yml dpt-psico-u2004.yml dpt-religio-u2004.yml dpt-tecno-u2004.yml esobatx-u2004.yml esobatx_dept-u2004.yml esobatx_wifi-u2004.yml portatils-docents-u2004.yml saladeguardies-u2004.yml saladeprofessors-u2004.yml secretaria-u2004.yml snowden-u2004.yml stallman-u2004.yml snowden-u2004.yml tesla-u2004.yml torvalds-u2004.yml turing-u2004.yml
do
	# Comprobamos si hay peticiones pendientes
	n=`$PYTHON $MANAGE getnumberofrequests $x`
	echo "Para la etiqueta $x hay $n peticiones pendientes."
	if [ $n -gt 0 ]
	then
		hosts=`$PYTHON $MANAGE gethosts $x`
		echo "Lanzo ansible-playbook -i $playbooks/hosts $playbooks/$x --limit=$hosts"
		ansible-playbook -i $playbooks/hosts $playbooks/$x --limit=$hosts &
	else
		echo No hay nada que hacer
	fi
done

echo "Esperando que acaben las tareas ansible-playbook..."
wait
echo "Todos los playbooks de ansible se han completado."
