#!/bin/bash
#
# /etc/systemd/system/vasilisa.service lanza Vasilisa en cada arranque.
#
# El script es responsable de algunas tareas de mantenimiento:
#
# - Si el espacio disponible está por debajo del umbral borra los ficheros
#   en el directorio descargas y en la papelera de cada usuario.
#
# - Si LXD está instalado detiene cada uno de los contenedores encendidos.
#
# - Si hay iconos de usuario personalizados en /var/lib/AccountsService/icons
#   los borra.
#


THRESHOLD=209715200 # 200GiB
DOWNLOAD_DIR='Baixades'

SCRIPT=`basename $0`

function log () {
        logger -t $SCRIPT $1
}

log "There is something to do?"

DISK_FREE=`df | grep -E \/$ | sed "s/  */ /g" | cut -f4 -d' ' | cut -f1 -d'%'`
log "Disk free: $DISK_FREE Threshold: $THRESHOLD"

if [ $DISK_FREE -le $THRESHOLD ]
then
	log "Disk free under threshold. Deleting files in $DOWNLOAD_DIR & empty trash for every user."	

	for user in `ls /home`
	do
		# Empty $DOWNLOAD_DIR
		download_dir="/home/$user/$DOWNLOAD_DIR"
		if [ -d $download_dir ]
		then
			size=`du -hs $download_dir 2>/dev/null`
			log "removing $size"
			rm -rf $download_dir/*
			log "removed"
		fi

		# Delete Trash
		trash_dir="/home/$user/.local/share/Trash"
		if [ -d $trash_dir ]
		then
			size=`du -hs $trash_dir 2>/dev/null`
			log "removing $size"
			rm -rf $trash_dir
			log "removed"
		fi
	done

	log "No more users"
	DISK_FREE=`df -h | grep -E \/$ | sed "s/  */ /g" | cut -f5 -d' ' | cut -f1 -d'%'`

	# Clean apt cache
	log "apt-get clean"
	apt-get clean

	log "Final disk usage: $DISK_FREE%"
fi

#
# Checks for LXD RUNNING containers to stop
#
LXC="/usr/bin/lxc"
if [ -f $LXC ]
then
	log "There are LXD running containers?"

	# We need to wait for lxd containers
	sleep 60

	for container in `$LXC list -c n,s --format csv | grep RUNNING | cut -f1 -d','`
	do
		# Stop container
		log "Stop container $container"
		$LXC stop $container && log "stopped $container"
	done

fi

#
# Delete user icons
#
ICONSDIR="/var/lib/AccountsService/icons"
for x in `ls $ICONSDIR`
do
	log "Deleting $ICONSDIR/$x"
	rm $ICONSDIR/$x
done

log "There is nothing to do."
