#
# Instala paquetes en Fedora
#

- name: Instalación de paquetes que están en los repos de Fedora
  dnf:
    state: present
    update_cache: yes
    name:
      - dia
      - dia-CMOS
      - dia-Digital
      - dia-electric2
      - dia-electronic
      - dia-gnomeDIAicons
      - dia-optics
      - dialog
      - golang-bin
      - golang-github-prometheus-node-exporter
      - htop
      - httpie
      - java-11-openjdk
      - librecad
      - librecad-parts
      - librecad-patterns
      - ncdu
      - python3-pip
      - python3-pylint
      - python3-virtualenv
      - ripgrep
      - ruby
      - vim-enhanced
      - xorriso


