- name: Alta de convidat
  action: user name=convidat create_home=no groups=cdrom,dialout append=yes shell=/bin/bash comment="Usuari convidat" password=""

- name: Edición de /etc/gdm3/PostLogin/Default
  blockinfile:
    dest: /etc/gdm3/PostLogin/Default
    create: yes
    owner: root
    group: root
    mode: 755
    block: |
      # Usuari convidat
      guestuser='convidat'

      if [ $USER = $guestuser ]
      then
        # Se borra el directorio por si ha quedado desde la última sesión
        [ -d /home/$guestuser ] && rm -rf /home/$guestuser
        # Se recrea el directorio
        mkdir /home/$guestuser
        cp /etc/skel/.bash_logout /home/$guestuser
        cp /etc/skel/.bashrc /home/$guestuser
        cp /etc/skel/.profile /home/$guestuser
        mkdir /home/$guestuser/.config
        echo 'yes' > /home/$guestuser/.config/gnome-initial-setup-done
        chown -R $guestuser:$guestuser /home/$guestuser
      fi

- name: Edición de /etc/gdm3/PostSession/Default
  blockinfile:
    dest: /etc/gdm3/PostSession/Default
    owner: root
    group: root
    mode: 755
    insertafter: '^#!/bin/sh$'
    block: |
      guestuser='convidat'

      if [ $USER = $guestuser ]
      then
        rm -rf /home/$guestuser
      fi

- name: Copia /etc/systemd/system/convidat.path
  copy:
    src: files/convidat.path
    dest: /usr/lib/systemd/system
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Copia /etc/systemd/system/convidat.service
  copy:
    src: files/convidat.service
    dest: /usr/lib/systemd/system
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Activa /etc/systemd/system/convidat.path
  systemd:
    enabled: yes
    state: started
    #scope: global
    name: convidat.path