# Copia el snap de glpi-agent
- name: Copia el snap de glpi-agent en /opt/
  copy:
    src: files/glpi-agent_1.2_amd64.snap
    dest: /opt/glpi-agent_1.2_amd64.snap
    owner: root
    group: root
    mode: u=rwx,g=r,o=r
  notify:
    - instala glpi-agent
    - configura glpi-agent

# Equipos Fedora: Añade el dominio a /etc/hosts para utilizar la VPN
- name: Añade 10.0.0.5 glpi.elpuig.xeill.net a /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: 10.0.0.5 glpi.elpuig.xeill.net
  when: ansible_distribution == 'Fedora'
