# Copia el snap de glpi-agent
- name: Copia el snap de glpi-agent en /opt/
  copy:
    src: files/glpi-agent_1.2_amd64.snap
    dest: /opt/glpi-agent_1.2_amd64.snap
    owner: root
    group: root
    mode: u=rwx,g=r,o=r
  notify:
    - instala glpi-agent
    - configura glpi-agent

