# Instalación de paquetes Flatpak
#
#

# Ubuntu 20.04 necesita una versión nueva de flatpak para instalar chromium
#

#
# Añade PPA Flatpak ppa:alexlarsson/flatpak y configura 50unattended-upgrades
#
- name: Instala PPA Flatpak ppa:alexlarsson/flatpak
  apt_repository:
    repo: ppa:alexlarsson/flatpak
  when: ansible_distribution_version == "20.04"

- name: Añade LP-PPA-alexlarsson-flatpak:focal a /etc/apt/apt.conf.d/50unattended-upgrades
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    insertafter: '^Unattended-Upgrade::Allowed-Origins'
    line: '        "LP-PPA-alexlarsson-flatpak:focal";'
  when: ansible_distribution_version == "20.04"

- name: Actualiza (o instala) la última versión de flatpak
  apt:
    state: latest
    update_cache: yes
    pkg:
      - flatpak
  when: ansible_distribution == "Ubuntu"


# Instalación de paquetes Flatpak

#- name: Instala flatpaks
#  block:
#
#        - name: Instala flatpak de ardour
#          flatpak:
#                  name: https://dl.flathub.org/repo/appstream/org.ardour.Ardour.flatpakref
#                  state: present
#
#        - name: Instala flatpak de geogebra
#          flatpak:
#            name: https://dl.flathub.org/repo/appstream/org.geogebra.GeoGebra.flatpakref
#            state: present
#
#  rescue:
#    - name: Repara el repositorio flatpak
#      shell: flatpak repair

- name: Instala flatpak de ardour
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.ardour.Ardour.flatpakref
          state: present

- name: Instala flatpak de arduino-ide
  flatpak:
          name: https://dl.flathub.org/repo/appstream/cc.arduino.arduinoide.flatpakref
          state: present

- name: Instala flatpak de atom
  flatpak:
          name: https://dl.flathub.org/repo/appstream/io.atom.Atom.flatpakref
          state: present

- name: Instala flatpak de audacity
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.audacityteam.Audacity.flatpakref
          state: present

- name: Instala flatpak de blender
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.blender.Blender.flatpakref
          state: present

- name: Instala flatpak de bluej
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.bluej.BlueJ.flatpakref
          state: present

#- name: Instala flatpak de brave (beta)
#  flatpak:
#          name: https://flathub.org/beta-repo/appstream/com.brave.Browser.flatpakref
#          state: present

- name: Instala flatpak de calibre
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.calibre_ebook.calibre.flatpakref
          state: present

- name: Instala flatpak de chromium
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.chromium.Chromium.flatpakref
          state: present

- name: Instala flatpak de code-oss
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.visualstudio.code-oss.flatpakref
          state: present

- name: Instala flatpak de darktable
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.darktable.Darktable.flatpakref
          state: present

- name: Instala flatpak de dbeaver
  flatpak:
          name: https://dl.flathub.org/repo/appstream/io.dbeaver.DBeaverCommunity.flatpakref
          state: present

- name: Instala flatpak de digikam
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.kde.digikam.flatpakref
          state: present

- name: Instala flatpak de diylayoutcreator
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.diy_fever.DIYLayoutCreator.flatpakref
          state: present

- name: Instala flatpak de eclipse
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.eclipse.Java.flatpakref
          state: present

- name: Instala flatpak de filezilla
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.filezillaproject.Filezilla.flatpakref
          state: present

- name: Instala flatpak de flameshot
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.flameshot.Flameshot.flatpakref
          state: present

- name: Instala flatpak de freecad
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.freecadweb.FreeCAD.flatpakref
          state: present

- name: Instala flatpak de fritzing
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.fritzing.Fritzing.flatpakref
          state: present

- name: Instala flatpak de gaphor
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.gaphor.Gaphor.flatpakref
          state: present

- name: Instala flatpak de geany
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.geany.Geany.flatpakref
          state: present

- name: Instala flatpak de geogebra
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.geogebra.GeoGebra.flatpakref
          state: present

- name: Instala flatpak de gimp
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.gimp.GIMP.flatpakref
          state: present

- name: Instala flatpak de godot
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.godotengine.Godot.flatpakref
          state: present

- name: Instala flatpak de inkscape
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.inkscape.Inkscape.flatpakref
          state: present

- name: Instala flatpak de IntelliJ-IDEA-Community
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.jetbrains.IntelliJ-IDEA-Community.flatpakref
          state: present

- name: Instala flatpak de Klavaro
  flatpak:
          name: https://dl.flathub.org/repo/appstream/net.sourceforge.Klavaro.flatpakref
          state: present

- name: Instala flatpak de LMMS
  flatpak:
          name: https://dl.flathub.org/repo/appstream/io.lmms.LMMS.flatpakref
          state: present

- name: Instala flatpak de kalzium
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.kde.kalzium.flatpakref
          state: present

- name: Instala flatpak de herramientas kde
  flatpak:
          state: present
          name: "{{ item  }}"
  loop:
          - https://dl.flathub.org/repo/appstream/org.kde.kbruch.flatpakref
          - https://dl.flathub.org/repo/appstream/org.kde.kcalc.flatpakref
          - https://dl.flathub.org/repo/appstream/org.kde.kdenlive.flatpakref
          - https://dl.flathub.org/repo/appstream/org.kde.kig.flatpakref
            #- https://dl.flathub.org/repo/appstream/org.kde.kontact.flatpakref
          - https://dl.flathub.org/repo/appstream/org.kde.ktouch.flatpakref

- name: Instala flatpak de kicad
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.kicad.KiCad.flatpakref
          state: present

- name: Instala flatpak de kooha
  flatpak:
          name: https://dl.flathub.org/repo/appstream/io.github.seadve.Kooha.flatpakref
          state: present

- name: Instala flatpak de krita
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.kde.krita.flatpakref
          state: present

- name: Instala flatpak de libreoffice
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.libreoffice.LibreOffice.flatpakref
          state: present

- name: Instala flatpak de librepcb
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.librepcb.LibrePCB.flatpakref
          state: present

- name: Instala flatpak de maps
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.gnome.Maps.flatpakref
          state: present

- name: Instala flatpak de musescore
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.musescore.MuseScore.flatpakref
          state: present

- name: Instala flatpak de natron
  flatpak:
          name: https://dl.flathub.org/repo/appstream/fr.natron.Natron.flatpakref
          state: present

- name: Instala flatpak de netbeans
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.apache.netbeans.flatpakref
          state: present

- name: Instala flatpak de octave
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.octave.Octave.flatpakref
          state: present

- name: Instala flatpak de openscad
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.openscad.OpenSCAD.flatpakref
          state: present

- name: Instala flatpak de openshot
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.openshot.OpenShot.flatpakref
          state: present

- name: Instala flatpak de plots
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.github.alexhuntley.Plots.flatpakref
          state: present

- name: Instala flatpak de obs-studio
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.obsproject.Studio.flatpakref
          state: present

- name: Instala flatpak de openboard
  flatpak:
          name: https://dl.flathub.org/repo/appstream/ch.openboard.OpenBoard.flatpakref
          state: present

- name: Instala flatpak de passwordsafe
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.gnome.PasswordSafe.flatpakref
          state: present

- name: Instala flatpak de pdfarranger
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.github.jeromerobert.pdfarranger.flatpakref
          state: present

- name: Instala flatpak de pdfmixtool
  flatpak:
          name: https://dl.flathub.org/repo/appstream/eu.scarpetta.PDFMixTool.flatpakref
          state: present

- name: Instala flatpak de pdfslicer
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.github.junrrein.PDFSlicer.flatpakref
          state: present

- name: Instala flatpak de peek
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.uploadedlobster.peek.flatpakref
          state: absent

- name: Instala flatpak de prusaslicer
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.prusa3d.PrusaSlicer.flatpakref
          state: present

- name: Instala flatpak de qalculate
  flatpak:
          name: https://dl.flathub.org/repo/appstream/io.github.Qalculate.flatpakref
          state: present

- name: Instala flatpak de remmina
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.remmina.Remmina.flatpakref
          state: present

- name: Instala flatpak de scratch
  flatpak:
          name: https://dl.flathub.org/repo/appstream/edu.mit.Scratch.flatpakref
          state: present

- name: Instala flatpak de soundrecorder
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.gnome.SoundRecorder.flatpakref
          state: present

- name: Instala flatpak de sweethome3d
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.sweethome3d.Sweethome3d.flatpakref
          state: present

- name: Instala flatpak de shotcut
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.shotcut.Shotcut.flatpakref
          state: present

- name: Instala flatpak de transmission
  flatpak:
          name: https://dl.flathub.org/repo/appstream/com.transmissionbt.Transmission.flatpakref
          state: present

- name: Instala flatpak de tuxguitar
  flatpak:
          name: https://dl.flathub.org/repo/appstream/ar.com.tuxguitar.TuxGuitar.flatpakref
          state: present

- name: Instala flatpak de umbrello
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.kde.umbrello.flatpakref
          state: present

- name: Instala flatpak de vlc
  flatpak:
          name: https://dl.flathub.org/repo/appstream/org.videolan.VLC.flatpakref
          state: present
